export const imagesMap = [
	{
		weather: "Clear",
		period: "night",
		descriptions: ["clear sky", "sky is clear"],
		image_path: "./weather/background/clear-night.png",
		icon_path: "./weather/icons/clear-night.svg",
	},
	{
		weather: "Clear",
		period: "day",
		descriptions: ["clear sky", "sky is clear"],
		image_path: "./weather/background/clear-day.png",
		icon_path: "./weather/icons/clear-day.svg",
	},
	{
		weather: "Clouds",
		period: "night",
		descriptions: [
			"overcast clouds",
			"broken clouds",
			"overcast clouds",
			"scattered clouds",
		],
		image_path: "./weather/background/cloudy-night.png",
		icon_path: "./weather/icons/cloudy-night.svg",
	},
	{
		weather: "Clouds",
		period: "day",
		descriptions: [
			"overcast clouds",
			"broken clouds",
			"overcast clouds",
			"scattered clouds",
		],
		image_path: "./weather/background/cloudy-day.png",
		icon_path: "./weather/icons/cloudy-day.svg",
	},
	{
		weather: "Clouds",
		period: "night",
		descriptions: ["few clouds"],
		image_path: "./weather/background/partly-cloudy-night.png",
		icon_path: "./weather/icons/partly-cloudy.svg",
	},
	{
		weather: "Clouds",
		period: "day",
		descriptions: ["few clouds"],
		image_path: "./weather/background/partly-cloudy-day.png",
		icon_path: "./weather/icons/partly-cloudy.svg",
	},
	{
		weather: "Rain",
		period: "night",
		descriptions: [
			"light rain",
			"moderate rain",
			"heavy intensity rain",
			"very heavy rain",
			"extreme rain",
			"freezing rain",
			"shower rain",
			"light intensity shower rain",
			"heavy intensity shower rain",
			"ragged shower rain",
		],
		image_path: "./weather/background/rainy-night.png",
		icon_path: "./weather/icons/rainy-night.svg",
	},
	{
		weather: "Rain",
		period: "day",
		descriptions: [
			"light rain",
			"moderate rain",
			"heavy intensity rain",
			"very heavy rain",
			"extreme rain",
			"freezing rain",
			"shower rain",
			"light intensity shower rain",
			"heavy intensity shower rain",
			"ragged shower rain",
		],
		image_path: "./weather/background/rainy-day.png",
		icon_path: "./weather/icons/rainy-day.svg",
	},
	{
		weather: "Thunderstorm",
		period: "night",
		descriptions: [
			"thunderstorm",
			"thunderstorm with light rain",
			"thunderstorm with rain",
			"thunderstorm with heavy rain",
			"light thunderstorm",
			"heavy thunderstorm",
			"ragged thunderstorm",
		],
		image_path: "./weather/background/thunderstorm-night.png",
		icon_path: "./weather/icons/thunderstorm.svg",
	},
	{
		weather: "Thunderstorm",
		period: "day",
		descriptions: [
			"thunderstorm",
			"thunderstorm with light rain",
			"thunderstorm with rain",
			"thunderstorm with heavy rain",
			"light thunderstorm",
			"heavy thunderstorm",
			"ragged thunderstorm",
		],
		image_path: "./weather/background/thunderstorm-day.png",
		icon_path: "./weather/icons/thunderstorm.svg",
	},
];
